### ISSUE TITLE
Zulu JRE not found

### ISSUE THREAD

**Issue by kaikramer** [Bill-Stewart/JavaInfo#2]
I have Azure Zulu in first position in the Path, JAVA_HOME is not set, but for some reason JavaInfo finds AdoptOpenJDK:

```
C:\Users\kk>echo %JAVA_HOME%
%JAVA_HOME%

C:\Users\kk>echo %PATH%
C:\Program Files\Zulu\zulu-15\bin\;...

C:\Users\kk>java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment Zulu15.28+51-CA (build 15.0.1+9)
OpenJDK 64-Bit Server VM Zulu15.28+51-CA (build 15.0.1+9, mixed mode, sharing)
```

![grafik](https://user-images.githubusercontent.com/7840192/104077939-ec7ad680-521b-11eb-9760-cf3b3c6d2407.png)

**Comment by Bill-Stewart** [comment]
Interesting...are you running `JavaInfoTest.exe` from that same console window?

**Comment by kaikramer** [comment]
Nvm, my mistake...

**Comment by Bill-Stewart** [comment]
My guess is the `Path` environment variable hadn't propagated to the process from which you ran the test program.

It might be a good idea to read the environment variables and the `Path` directly from the registry as an additional check. That should "fix" the issue you experienced here.

**Comment by kaikramer** [comment]
Yep, that was indeed the problem. I am using Total Commander which recognizes changes of JAVA_HOME instantly, but changes of Path only after a restart.

I don't think this is a real issue as this does not happen with Windows Explorer. No need to do something about it.

**Comment by Bill-Stewart** [comment]
I could attempt to read the environment variable values and path directly from the registry if they aren't in the environment of the current process. This would fix the edge case where someone installs a Java instance, updates the environment or path, but JavaInfo.dll doesn't detect it because the change doesn't exist in the environment inherited by the process JavaInfo.dll is running in.

**Comment by Bill-Stewart** [comment]
I have thought about doing this (reading the environment variables from the registry directly) and it may have some unintended consequences (it may cause more confusion and cause more problems than it solves). Never mind...
